In [1]:
import numpy as np

In [2]:
# ndarray 내 data -> int형, unsigned int형(0~2^16까지 정수), float형, complex type 제공
# ndarray 내 data type -> dtype 속성으로 확인 가능
# list -> 서로 다른 data type 가질 수 있음

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [4]:
# cuz of 연산의 특성, same data type만 가능)
# list1 = integer 숫자인 1,2,3 값으로 가짐
# dif. type of data -> size 가 더 큰 data type으로 형 변환 일괄 적용

list2 = [1,2,'test']    #---int형 & string형--;;
array2 = np.array(list2)
print(array2, array2.dtype)
# int형 -> string형

list3 = [1,2,3.0]    #---int형 & float형--;;
array3 = np.array(list3)
print(array3, array3.dtype)
# int형 -> float64형

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [5]:
# astype() := ndarray 내 data값's type 변경 가능
# data type 변경시, 대용향 data의 ndarray를 만들 때 많은 memory 사용 -> memory를 절약해야할 때 사용

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32
