In [1]:
import numpy as np

In [3]:
# 특정 크기와 차원을 가진 ndarray를 [연속값/0/1]로 초기화해 사용할 경우, arrange(), zeros(), ones() 사용
# (make data for testing or 대규모 data 일괄적으로 reset)

# arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# default 함수 인자 = stop값
# 0 ~ stop값(= 10+(-1) = 9) 의 연속 숫자 값
# start값도 부여해 0이 아닌 값부터 시작한 연속 값을 부여할 수 있음

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [5]:
# zero()
# tuple 형태의 shape값 입력 -> 모든 값을 0으로 채운 shape를 가진 ndarray 반환

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [6]:
# ones()
# tuple 형태의 shape값 입력 -> 모든 값을 1로 채운 shape를 가진 ndarray 반환
# dtype 정하지 x -> default로 float64 형의 data로 ndarray 채움

one_array = np.zeros((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)
