In [1]:
import numpy as np

In [3]:
# reshape() 메서드 := ndarray를 특정 dimension & size 로 변환

array1 = np.arange(10)
print('array1:\n', array1)

# 0~9까지의 1차원 ndarray를 2*5 행렬 2차원 ndarray로 변환
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

# 0~9까지의 1차원 ndarray를 5*2 행렬 2차원 ndarray로 변환
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
# reshape()는 지정된 size로 변경이 불가능하면 error 발생

array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [5]:
array1 = np.arange(10)
print(array1)

# array1과 호환될 수 있는 2차원 ndarray로 변환 + 고정된 5개의 column에 맞는 row를 새롭게 생성해 변환
array2 = array1.reshape(-1, 5)
print('array2.shape:', array2.shape)

# array1과 호환될 수 있는 2차원 ndarray로 변환 + 고정된 5개의 row에 맞는 column을 새롭게 생성해 변환
array3 = array1.reshape(5, -1)
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


In [6]:
# 4개의 column을 가진 row로는 변경할 수 없기에 error 발생
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [9]:
# ndarray를 tolist() 메서드를 사용해 리스트 자료형으로 만들 수 있음

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
# reshape(-1, 1)은 원본 ndarray가 어떤 shape라도 2차원 + 여러 row를 가지되 only 1개의 column을 가진 ndarray로 변환된
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
